language: python
install:
  - pip install mkdocs
  - pip install awscli
script:
  - mkdocs build --verbose --clean --strict
deploy:
  provider: script
  script: aws s3 sync site s3://docs.leapdao.org --region=eu-west-1 --acl=public-read
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths '/*'